//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emoji_2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emoji_2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_0 {
            get {
                object obj = ResourceManager.GetObject("cat_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_1 {
            get {
                object obj = ResourceManager.GetObject("cat_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_2 {
            get {
                object obj = ResourceManager.GetObject("cat_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_3 {
            get {
                object obj = ResourceManager.GetObject("cat_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_4 {
            get {
                object obj = ResourceManager.GetObject("cat_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_5 {
            get {
                object obj = ResourceManager.GetObject("cat_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_6 {
            get {
                object obj = ResourceManager.GetObject("cat_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_7 {
            get {
                object obj = ResourceManager.GetObject("cat_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///😀 😄 😊 😌 😚 🤓 😐 😳 😔 😖 😱 😧 😭 🤒 😈 👻 😹 😿 👍🏻 👌🏻 ☝🏻 🖕🏻 💅🏻 👁 👶🏻 👱🏻 👮🏻 👼🏻 💃🏻 🙇🏻 🙎🏻 👩‍❤️‍👩 👪 👩‍👩‍👦 👨‍👨‍👦 👚 👙 👠 👒 🎒 👓
        ///😬 😅 🙂 😍 😜 😎 😑 😞 😕 😫 😨 😢 😵 🤕 👿 👽 😻 😾 👎🏻 ✋🏻 👆🏻 🖐🏻 👄 👀 👦🏻 👴🏻 👷🏻 👸🏻 👯 💁🏻 🙍🏻 👨‍❤️‍👨 👨‍👩‍👧 👩‍👩‍👧 👨‍👨‍👧 👕 👘 👡 🎩 👝 🕶
        ///😁 😆 🙃 😘 😝 🤗 😒 😟 🙁 😩 😰 😥 😲 😴 👹 🤖 😼 🙌🏻 👊🏻 👐🏻 👇🏻 🤘🏻 👅 👤 👧🏻 👵🏻 💂🏻 👰🏻 👫 🙅🏻 💇🏻 💏 👨‍👩‍👧‍👦 👩‍👩‍👧‍👦 👨‍👨‍👧‍👦 👖 💄 👢 🎓 👛 💍
        ///😂 � [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string catString_0 {
            get {
                return ResourceManager.GetString("catString_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///🐶 🐻 🐮 🐵 🐔 🐥 🐝 🕷 🐠 🐋 🐂 🐐 🐀 🐕 🐾 🌲 ☘ 🍂 🌹 🍄 🌎 🌗 🌔 🌞 ✨ 🌥 🌩 🌨 🌪 💦
        ///🐱 🐼 🐷 🙈 🐧 🐺 🐛 🦂 🐟 🐊 🐄 🐏 🐁 🐩 🐉 🌳 🍀 🍁 🌷 🌰 🌍 🌘 🌚 🌙 ☄ 🌦 ⚡️ ☃ 🌫 🌊
        ///🐭 🐨 🐽 🙉 🐦 🐗 🐌 🦀 🐡 🐆 🐪 🐑 🐓 🐈 🐲 🌴🎍 🌾 🌼 🎃 🌏 🌑 🌝 ⭐️ ☀️ ☁️ 🔥 ⛄️ ☂
        ///🐹 🐯 🐸 🙊 🐤 🐴 🐞 🐍 🐬 🐅 🐫 🐎 🦃 🐇 🌵 🌱 🎋 🌺 🌸 🐚 🌕 🌒 🌛 🌟 🌤 🌧 💥 🌬 ☔️
        ///🐰 🦁 🐙 🐒 🐣 🦄 🐜 🐢 🐳 🐃 🐘 🐖 🕊 🐿 🎄 🌿 🍃 🌻 💐 🕸 🌖 🌓 🌜 💫 ⛅️ ⛈ ❄️ 💨 💧.
        /// </summary>
        internal static string catString_1 {
            get {
                return ResourceManager.GetString("catString_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///🍏 🍌 🍒 🌶 🧀 🍔 🌮 🍣 🍘 🍦 🍭 🍺 🍾 🍴
        ///🍎 🍉 🍑 🌽 🍗 🍟 🌯 🍱 🍢 🍰 🍫 🍻 🍶 🍽
        ///🍐 🍇 🍍 🍠 🍖 🌭 🍜 🍛 🍡 🎂 🍿 🍷 🍵
        ///🍊 🍓 🍅 🍯 🍤 🍕 🍲 🍙 🍧 🍮 🍩 🍸 ☕️
        ///🍋 🍈 🍆 🍞 🍳 🍝 🍥 🍚 🍨 🍬 🍪 🍹 🍼.
        /// </summary>
        internal static string catString_2 {
            get {
                return ResourceManager.GetString("catString_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///⚽️ 🏐 🏓 🎿 🎣 ⛹🏻 🕴 🎗 🎨 🎹 🎬 🎰
        ///🏀 🏉 🏸 ⛷ 🚣🏻 🏋🏻 🏆 🏵 🎪 🎷 🎮 🎳
        ///🏈 🎱 🏒 🏂 🏊🏻 🚴🏻 🎽 🎫 🎤 🎺 👾
        ///⚾️ ⛳️ 🏑 ⛸ 🏄🏻 🚵🏻 🏅 🎟 🎧 🎸 🎯
        ///🎾 🏌 🏏 🏹 🛀🏻 🏇🏻 🎖 🎭 🎼 🎻 🎲.
        /// </summary>
        internal static string catString_3 {
            get {
                return ResourceManager.GetString("catString_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///🚗 🏎 🚚 🚨 🚡 🚝 🚂 🚁 ⛵️ 🚀 ⛽️ 🚢 🌁 ⛰ 🏕 🌅 🌇 🌌 🏘 🏠 🏣 🏪 ⛪️
        ///🚕 🚓 🚛 🚔 🚠 🚄 🚆 🛩 🛥 🛰 🚏 🎡 🗼 🏔 ⛺️ 🌄 🌆 🌠 🏰 🏡 🏤 🏫 🕌
        ///🚙 🚑 🚜 🚍 🚟 🚅 🚇 ✈️ 🚤 💺 🚦 🎢 🏭 🗻 🏞 🏜 🏙 🎇 🏯 🏚 🏥 🏩 🕍
        ///🚌 🚒 🏍 🚘 🚃 🚈 🚊 🛫 ⛴ ⚓️ 🚥 🎠 ⛲️ 🌋 🛣 🏖 🌃 🎆 🏟 🏢 🏦 💒 🕋
        ///🚎 🚐 🚲 🚖 🚋 🚞 🚉 🛬 🛳 🚧 🏁 🏗 🎑 🗾 🛤 🏝 🌉 🌈 🗽 🏬 🏨 🏛 ⛩.
        /// </summary>
        internal static string catString_4 {
            get {
                return ResourceManager.GetString("catString_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///⌚️ 🖥 🗜 📼 📽 📠 🎛 ⏳ 💡 💸 💰 🔨 ⚙ 🗡 ⚰ 💈 💊 🚽 🛋 🖼 🎈 🎉 ✉️ 📮 📦 📃 📄 🗃 📁 📓 📔 📎 📌 🔐 🖋 🖌
        ///📱 🖨 💽 📷 🎞 📺 ⏱ ⌛️ 🔦 💵 💳 ⚒ ⛓ ⚔ ⚱ ⚗ 💉 🚿 🛌 🗺 🎏 🎎 📩 📪 📯 📑 📅 🗳 📂 📕 📒 🖇 📍 🔒 ✒️ 🔍
        ///📲 🖱 💾 📸 📞 📻 ⏲ 📡 🕯 💴 💎 🛠 🔫 🛡 🏺 🔭 🌡 🛁 🛏 ⛱ 🎀 🎐 📨 📫 📥 📊 📆 🗄 🗂 📗 📚 ✂️ 🚩 🔓 📝 🔎
        ///💻 🖲 💿 📹 ☎️ 🎙 ⏰ 🔋 🗑 💶 ⚖ ⛏ 💣 🚬 🔮 🔬 🏷 🔑 🚪 🗿 🎁 🎌 📧 📬 📤 📈 🗓 📋 🗞 📘 📖 📐 🏳 🔏 ✏️
        ///⌨ 🕹 📀 🎥 📟 🎚 🕰 🔌 🛢 💷 🔧 🔩 🔪 ☠ 📿 🕳 🔖 🗝 🛎 🛍 🎊 🏮 💌 📭 📜 📉 📇 🗒 📰 📙 🔗 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string catString_5 {
            get {
                return ResourceManager.GetString("catString_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///❤️ 💔 💗 ☮ ✡ 🛐 ♋️ ♐️ ⚛ 📴 🈺 💮 🈵 🆑 🚫 🚷 📵 ‼️ 🔱 🔰 ✳️ ➿ 🛂 🚭 🚺 📶 🆒 2️⃣ 7️⃣ ▶️ ⏭ 🔁 ⏫ ⬇️ ↕️ ⤴️ 🔤 🎶 ➕ 💱 🔙 🔘 🔸 ▪️ ◼️ 🔳 📣 🀄️ 🎴 🕐 🕕 🕚 🕟 🕤
        ///💛 ❣ 💖 ✝ 🔯 ⛎ ♌️ ♑️ 🈳 📳 🈷 🉐 🈲 🅾 ❌ 🚯 ❗️ ⁉️ ⚜ ♻️ ❎ 🌐 🛃 🚾 🚼 🈁 🆕 3️⃣ 8️⃣ ⏸ ⏮ 🔂 ⏬ ↗️ ↔️ ⤵️ 🔡 〰 ➖ © 🔛 ⚪️ 🔹 ▫️ ◻️ 🔈 📢 ♠️ 👁‍🗨 🕑 🕖 🕛 🕠 🕥
        ///💚 💕 💘 ☪ 🕎 ♈️ ♍️ ♒️ 🈹 🈶 ✴️ ㊙️ 🅰 🆘 ⭕️ 🚳 ❕ 💯 〽️ 🈯️ ✅ Ⓜ️ 🛄 🅿️ 🚻 🆖 🆓 4️⃣ 9️⃣ ⏯ ⏩ ◀️ ➡️ ↘️ 🔄 #️⃣ 🔠 ➰ ➗ ® 🔝 ⚫️ 🔶 ⬛️ ◾️ 🔉 🔔 ♣️ 💭 🕒 🕗 🕜 🕡 🕦
        ///💙 💞 💝 🕉 ☯ ♉️ ♎️ ♓️ ☢ 🈚️ 🆚 ㊗️ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string catString_6 {
            get {
                return ResourceManager.GetString("catString_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​
        ///🇦🇫 🇦🇩 🇦🇷 🇦🇿 🇧🇾 🇧🇹 🇮🇴 🇧🇮 🇨🇻 🇨🇱 🇰🇲 🇨🇮 🇨🇿 🇪🇨 🇪🇪 🇫🇯 🇹🇫 🇬🇭 🇬🇵 🇬🇼 🇭🇺 🇮🇶 🇯🇲 🇰🇪 🇱🇦 🇱🇾 🇲🇰 🇲🇱 🇲🇺 🇲🇨 🇲🇿 🇳🇱 🇳🇬 🇳🇴 🇵🇦 🇵🇳 🇷🇪 🇸🇲 🇸🇨 🇸🇮 🇰🇷 🇸🇭 🇸🇩 🇸🇾 🇹🇱 🇹🇳 🇻🇮 🇺🇸 🇻🇪 🇿🇲
        ///🇦🇽 🇦🇴 🇦🇲 🇧🇸 🇧🇪 🇧🇴 🇻🇬 🇰🇭 🇧🇶 🇨🇳 🇨🇬 🇭🇷 🇩🇰 🇪🇬 🇪🇹 🇫🇮 🇬🇦 🇬🇮 🇬🇺 🇬🇾 🇮🇸 🇮🇪 🇯🇵 🇰🇮 🇱🇻 🇱🇮 🇲🇬 🇲🇹 🇾🇹 🇲🇳 🇲🇲 🇳🇨 🇳🇺 🇴🇲 🇵🇬 🇵🇱 🇷🇴 🇸🇹 🇸🇱 🇬🇸 🇸🇸 🇰🇳 🇸🇷 🇹🇼 🇹🇬 🇹🇷 🇺🇬 🇺🇾 🇻🇳 🇿🇼
        ///🇦🇱 🇦 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string catString_7 {
            get {
                return ResourceManager.GetString("catString_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_0 {
            get {
                object obj = ResourceManager.GetObject("race_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_0_s {
            get {
                object obj = ResourceManager.GetObject("race_0_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_1 {
            get {
                object obj = ResourceManager.GetObject("race_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_1_s {
            get {
                object obj = ResourceManager.GetObject("race_1_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_2 {
            get {
                object obj = ResourceManager.GetObject("race_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_2_s {
            get {
                object obj = ResourceManager.GetObject("race_2_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_3 {
            get {
                object obj = ResourceManager.GetObject("race_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_3_s {
            get {
                object obj = ResourceManager.GetObject("race_3_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_4 {
            get {
                object obj = ResourceManager.GetObject("race_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_4_s {
            get {
                object obj = ResourceManager.GetObject("race_4_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_5 {
            get {
                object obj = ResourceManager.GetObject("race_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap race_5_s {
            get {
                object obj = ResourceManager.GetObject("race_5_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ​  🏻 🏼 🏽 🏾 🏿.
        /// </summary>
        internal static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_0 {
            get {
                object obj = ResourceManager.GetObject("type_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_1 {
            get {
                object obj = ResourceManager.GetObject("type_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_2 {
            get {
                object obj = ResourceManager.GetObject("type_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_3 {
            get {
                object obj = ResourceManager.GetObject("type_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_4 {
            get {
                object obj = ResourceManager.GetObject("type_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_5 {
            get {
                object obj = ResourceManager.GetObject("type_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_6 {
            get {
                object obj = ResourceManager.GetObject("type_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_7 {
            get {
                object obj = ResourceManager.GetObject("type_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types {
            get {
                object obj = ResourceManager.GetObject("types", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types1 {
            get {
                object obj = ResourceManager.GetObject("types1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
